package p1;
// Generated 24-nov-2022 23:22:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Casas generated by hbm2java
 */
public class Casas  implements java.io.Serializable {


     private int idCasa;
     private Personajes fundador;
     private String nombre;
     private String colores;
     private Set personajeses = new HashSet(0);

    public Casas() {
    }

    public Casas(int idCasa) {
        this.idCasa = idCasa;
    }

    public Casas(int idCasa, String nombre) {
        this.idCasa = idCasa;
        this.nombre = nombre;
    }

	
    public Casas(int idCasa, Personajes personajes, String nombre, String colores) {
        this.idCasa = idCasa;
        this.fundador = personajes;
        this.nombre = nombre;
        this.colores = colores;
    }
    public Casas(int idCasa, Personajes personajes, String nombre, String colores, Set personajeses) {
       this.idCasa = idCasa;
       this.fundador = personajes;
       this.nombre = nombre;
       this.colores = colores;
       this.personajeses = personajeses;
    }
   
    public int getIdCasa() {
        return this.idCasa;
    }
    
    public void setIdCasa(int idCasa) {
        this.idCasa = idCasa;
    }
    public Personajes getPersonajes() {
        return this.fundador;
    }
    
    public void setPersonajes(Personajes personajes) {
        this.fundador = personajes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getColores() {
        return this.colores;
    }
    
    public void setColores(String colores) {
        this.colores = colores;
    }
    public Set getPersonajeses() {
        return this.personajeses;
    }
    
    public void setPersonajeses(Set personajeses) {
        this.personajeses = personajeses;
    }




}


