package p1;
// Generated 24-nov-2022 23:22:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escuelas generated by hbm2java
 */
public class Escuelas  implements java.io.Serializable {


     private int idEscuela;
     private Personajes personajes;
     private String nombre;
     private String localizacion;
     private Set personajeses = new HashSet(0);

    public Escuelas() {
    }

    public Escuelas(int idEscuela, String nombre) {
        this.idEscuela = idEscuela;
        this.nombre = nombre;
    }

    
    public Escuelas(int idEscuela){
        this.idEscuela=idEscuela;
    }
	
    public Escuelas(int idEscuela, Personajes personajes, String nombre, String localizacion) {
        this.idEscuela = idEscuela;
        this.personajes = personajes;
        this.nombre = nombre;
        this.localizacion = localizacion;
    }
    public Escuelas(int idEscuela, Personajes personajes, String nombre, String localizacion, Set personajeses) {
       this.idEscuela = idEscuela;
       this.personajes = personajes;
       this.nombre = nombre;
       this.localizacion = localizacion;
       this.personajeses = personajeses;
    }
   
    public int getIdEscuela() {
        return this.idEscuela;
    }
    
    public void setIdEscuela(int idEscuela) {
        this.idEscuela = idEscuela;
    }
    public Personajes getPersonajes() {
        return this.personajes;
    }
    
    public void setPersonajes(Personajes personajes) {
        this.personajes = personajes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }
    public Set getPersonajeses() {
        return this.personajeses;
    }
    
    public void setPersonajeses(Set personajeses) {
        this.personajeses = personajeses;
    }




}


