package p1;
// Generated 24-nov-2022 23:22:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private int idLibro;
     private String nombre;
     private int paginas;
     private String autores;
     private Set localizacioneses = new HashSet(0);
     private Set personajeses = new HashSet(0);

    public Libros() {
    }

    public Libros(int idLibro) {
        this.idLibro = idLibro;
    }

    
	
    public Libros(int idLibro, String nombre, int paginas, String autores) {
        this.idLibro = idLibro;
        this.nombre = nombre;
        this.paginas = paginas;
        this.autores = autores;
    }
    public Libros(int idLibro, String nombre, int paginas, String autores, Set localizacioneses, Set personajeses) {
       this.idLibro = idLibro;
       this.nombre = nombre;
       this.paginas = paginas;
       this.autores = autores;
       this.localizacioneses = localizacioneses;
       this.personajeses = personajeses;
    }
   
    public int getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPaginas() {
        return this.paginas;
    }
    
    public void setPaginas(int paginas) {
        this.paginas = paginas;
    }
    public String getAutores() {
        return this.autores;
    }
    
    public void setAutores(String autores) {
        this.autores = autores;
    }
    public Set getLocalizacioneses() {
        return this.localizacioneses;
    }
    
    public void setLocalizacioneses(Set localizacioneses) {
        this.localizacioneses = localizacioneses;
    }
    public Set getPersonajeses() {
        return this.personajeses;
    }
    
    public void setPersonajeses(Set personajeses) {
        this.personajeses = personajeses;
    }




}


