package p1;
// Generated 24-nov-2022 23:22:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personajes generated by hbm2java
 */
public class Personajes  implements java.io.Serializable {


     private int idPersonaje;
     private Casas casas;
     private Escuelas escuelas;
     private Libros libros;
     private String nombre;
     private String apellido;
     private String sexo;
     private int edad;
     private String descripcion;
     private Set casases = new HashSet(0);
     private Set escuelases = new HashSet(0);

    public Personajes() {
    }

	
    public Personajes(int idPersonaje, Casas casas, Escuelas escuelas, Libros libros, String nombre, String apellido, String sexo, int edad, String descripcion) {
        this.idPersonaje = idPersonaje;
        this.casas = casas;
        this.escuelas = escuelas;
        this.libros = libros;
        this.nombre = nombre;
        this.apellido = apellido;
        this.sexo = sexo;
        this.edad = edad;
        this.descripcion = descripcion;
    }
    public Personajes(int idPersonaje, Casas casas, Escuelas escuelas, Libros libros, String nombre, String apellido, String sexo, int edad, String descripcion, Set casases, Set escuelases) {
       this.idPersonaje = idPersonaje;
       this.casas = casas;
       this.escuelas = escuelas;
       this.libros = libros;
       this.nombre = nombre;
       this.apellido = apellido;
       this.sexo = sexo;
       this.edad = edad;
       this.descripcion = descripcion;
       this.casases = casases;
       this.escuelases = escuelases;
    }
   
    public int getIdPersonaje() {
        return this.idPersonaje;
    }
    
    public void setIdPersonaje(int idPersonaje) {
        this.idPersonaje = idPersonaje;
    }
    public Casas getCasas() {
        return this.casas;
    }
    
    public void setCasas(Casas casas) {
        this.casas = casas;
    }
    public Escuelas getEscuelas() {
        return this.escuelas;
    }
    
    public void setEscuelas(Escuelas escuelas) {
        this.escuelas = escuelas;
    }
    public Libros getLibros() {
        return this.libros;
    }
    
    public void setLibros(Libros libros) {
        this.libros = libros;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCasases() {
        return this.casases;
    }
    
    public void setCasases(Set casases) {
        this.casases = casases;
    }
    public Set getEscuelases() {
        return this.escuelases;
    }
    
    public void setEscuelases(Set escuelases) {
        this.escuelases = escuelases;
    }




}


